export default {
  ADD_BOOK: "ADD_BOOK",
  REMOVE_BOOK: "REMOVE_BOOK",
  UPDATE_BOOK: "UPDATE_BOOK",

  SET_INPUT_TITLE: "SET_INPUT_TITLE",
  SET_INPUT_CONTENT: "SET_INPUT_CONTENT",
  SET_INPUT_ID: "SET_INPUT_ID",
  RESET_INPUT: "RESET_INPUT",
};
